name: IFutureLicenses
version: 1.0
api: Spigot
api-version: 1.12.2
main: com.dragons0u1.ifuture.IFutureLicenses
authors: [IfutureStudios]

commands:
  license:
    description: Main command that handles all license usage
    usage: license <check:add:delete:give:remove> <license:player> <license>